theme: jekyll-theme-minimal
title: Dr. Ranja Sarkar
description: Author of ["A Handbook of Mathematical Models with Python"](https://github.com/PacktPublishing/A-Handbook-of-Mathematical-Models-with-Python/blob/main/README.md)





